#!/usr/bin/env bash
# Regenerate registry/repos.generated.yaml from live GitHub metadata.
#
# Enumerates every repository the authenticated user can reach — owned, via org
# membership, or as a collaborator — then keeps the ones belonging to an owner
# listed in registry/owners.txt, in that file's order. Add an org to owners.txt
# and its repos appear on the next sync; nothing else is hardcoded.
#
# This file is GENERATED — do not hand-edit it. Curated, human-owned context
# lives in registry/context/<repo>.md, which this script never touches.
#
# Runs locally. Requires: gh (authenticated), jq. The listing uses the
# `user/repos` endpoint authenticated by your `gh auth` session — no PAT and no
# CI secret. After it writes the file, commit and push like any other change.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OWNERS_FILE="$REPO_ROOT/registry/owners.txt"
OUT="$REPO_ROOT/registry/repos.generated.yaml"

die() {
	printf 'error: %s\n' "$1" >&2
	exit 1
}

command -v gh >/dev/null || die "gh not found"
command -v jq >/dev/null || die "jq not found"
[ -f "$OWNERS_FILE" ] || die "missing $OWNERS_FILE"

# One owner per line; `#` starts a comment, blank lines are ignored.
owners=()
while IFS= read -r line || [ -n "$line" ]; do
	line="${line%%#*}"
	line="$(printf '%s' "$line" | tr -d '[:space:]')"
	if [ -n "$line" ]; then
		owners+=("$line")
	fi
done <"$OWNERS_FILE"

if [ "${#owners[@]}" -eq 0 ]; then
	die "no owners configured. Edit $OWNERS_FILE and uncomment (or add) your
       GitHub username and any orgs you belong to, one per line."
fi

echo "fetching every accessible repository ..." >&2
# One combined, de-duplicated array of all accessible repos, newest push first.
ALL="$(gh api --paginate \
	'user/repos?per_page=100&affiliation=owner,collaborator,organization_member' \
	--jq '.[]' | jq -s 'unique_by(.full_name) | sort_by(.pushed_at) | reverse')"

owners_json="$(printf '%s\n' "${owners[@]}" | jq -R . | jq -s .)"
total="$(jq --argjson o "$owners_json" \
	'[.[] | select(.owner.login as $l | $o | index($l))] | length' <<<"$ALL")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
	echo "# GENERATED by scripts/sync-registry.sh — do not edit by hand."
	echo "# Every accessible repository under the owners in registry/owners.txt."
	echo "# Curated context lives in registry/context/<repo>.md."
	echo "# Regenerate: ./scripts/sync-registry.sh"
} >"$tmp"

if [ "$total" -eq 0 ]; then
	echo "owners: []" >>"$tmp"
else
	echo "owners:" >>"$tmp"
fi

for owner in "${owners[@]}"; do
	count="$(jq --arg o "$owner" '[.[] | select(.owner.login==$o)] | length' <<<"$ALL")"
	if [ "$count" -eq 0 ]; then
		echo "warning: no accessible repos for owner '$owner'" >&2
		continue
	fi

	{
		echo "  - name: $owner"
		echo "    repo_count: $count"
		echo "    repos:"
	} >>"$tmp"

	jq -r --arg o "$owner" '
    [.[] | select(.owner.login==$o)][] |
    "    - name: \(.name)\n" +
    "      url: \(.html_url)\n" +
    "      visibility: \(if .private then "private" else "public" end)\n" +
    "      role: \((.role_name // "-") | @json)\n" +
    "      archived: \(.archived)\n" +
    "      fork: \(.fork)\n" +
    "      language: \((.language // "-") | @json)\n" +
    "      default_branch: \((.default_branch // "-") | @json)\n" +
    "      pushed_at: \(.pushed_at)\n" +
    "      topics: [\((.topics // []) | join(", "))]\n" +
    "      description: \((.description // "") | @json)"
  ' <<<"$ALL" >>"$tmp"
done

# Owners that resolved to at least one repo — the ones actually emitted above.
emitted="$(jq --argjson o "$owners_json" \
	'[.[] | .owner.login] | unique | map(select(. as $l | $o | index($l))) | length' <<<"$ALL")"

{
	echo "totals:"
	echo "  repos: $total"
	echo "  owners: $emitted"
} >>"$tmp"

mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT ($total repos across $emitted owners)" >&2
